repos:
-   repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    - id: black
      language_version: python3.7
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    - id: end-of-file-fixer
      exclude: '.bumpversion.cfg'
    - id: trailing-whitespace
      exclude: '.bumpversion.cfg'
# Disable this until 3.8.0 is released (as explained in
# https://gitlab.com/pycqa/flake8/issues/450)
#-   repo: https://gitlab.com/pycqa/flake8
#    rev: 3.8.0
#    hooks:
#    - id: flake8
#      args: ['--config=tox.ini']
